"""Added location field to Tarantula

Revision ID: 9f7cd1c21dd6
Revises: baa65f0e6a37
Create Date: 2025-03-16 02:23:28.565455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7cd1c21dd6'
down_revision = 'baa65f0e6a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarantulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarantulas', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
