"""create favorites table

Revision ID: 2e2cca35f49d
Revises: 56b827a514b7
Create Date: 2025-02-27 16:52:16.196978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2cca35f49d'
down_revision = '56b827a514b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarantula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarantula_id'], ['tarantulas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tarantula_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
