"""Made name optional in tarantulas

Revision ID: d5a3d6947a38
Revises: 9f7cd1c21dd6
Create Date: 2025-03-16 02:33:16.672170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a3d6947a38'
down_revision = '9f7cd1c21dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarantulas', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=88),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarantulas', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=88),
               nullable=False)

    # ### end Alembic commands ###
